export const copy = {
  appName: 'Holobox Zorgsimulator',
  appShortName: 'Holobox Zorgsimulator',
  fictionalNotice: 'Alle cliëntgegevens in deze training zijn fictief.',
  educationalNotice:
    'Dit is een educatieve simulatie. Het is geen diagnostisch instrument en geen vervanging van professionele zorg.',
  startSimulation: 'Start simulatie',
  previousResults: 'Eerdere resultaten',
  aboutTraining: 'Over deze training',
  startIntake: 'Start intake',
  back: 'Terug',
  home: 'Naar start',
  tryAgain: 'Opnieuw proberen',
  saveResult: 'Resultaat opslaan',
  returnHome: 'Terug naar start',
  viewResult: 'Bekijk resultaat',
  deleteResult: 'Verwijder resultaat',
  confirmDelete: 'Ja, verwijderen',
  cancel: 'Annuleren',
  close: 'Sluiten',
  saveNotes: 'Notities bewaren',
  repeatResponse: 'Herhaal antwoord',
  makeNote: 'Maak een notitie',
  pause: 'Pauze',
  resume: 'Hervat',
  endSimulation: 'Beëindig simulatie',
  continueIntake: 'Ga verder',
  discardSession: 'Nieuwe start',
  resumeSession: 'Hervat intake',
  submitConclusion: 'Toon resultaat',
  skipLink: 'Ga naar inhoud',
  loading: 'De training wordt geladen…',
  errorTitle: 'De training kan niet worden getoond',
  errorUnknownRoute: 'Dit scherm bestaat niet. Je kunt teruggaan naar het startscherm.',
  storageUnavailable:
    'Lokale opslag is niet beschikbaar. Je kunt oefenen, maar resultaten worden niet bewaard.',
  storageCorrupted: 'Opgeslagen gegevens waren ongeldig en zijn veilig genegeerd.',
  pauseTitle: 'Intake gepauzeerd',
  pauseBody: 'De tijd staat stil. Ga verder wanneer je klaar bent, of stop de simulatie.',
  endTitle: 'Intake beëindigen?',
  endBody:
    'Je gaat naar de voorlopige conclusie met de keuzes tot nu toe. Ontbrekende stappen tellen als 0 punten.',
  deleteTitle: 'Resultaat verwijderen?',
  deleteBody:
    'Dit resultaat wordt van dit apparaat verwijderd. Dit kan niet ongedaan worden gemaakt.',
  resumeTitle: 'Onvoltooide intake gevonden',
  resumeBody: 'Er staat nog een lokale sessie open. Wil je die hervatten of opnieuw beginnen?',
  notesTitle: 'Notities',
  notesLimit: 'Maximaal 600 tekens per veld. Geen echte patiëntgegevens invullen.',
  resultsSaved: 'Resultaat is lokaal opgeslagen.',
  resultsSaveFailed: 'Opslaan is niet gelukt. Controleer of lokale opslag beschikbaar is.',
  emptyHistory: 'Er zijn nog geen opgeslagen pogingen op dit apparaat.',
  versionLabel: 'Versie',
  durationLabel: 'Duur',
  scoreLabel: 'Totaalscore',
  clientFictional: 'fictief',
  emotionLive: 'Emotie van de cliënt',
  progressLabel: 'Voortgang van het gesprek',
  optionsLegend: 'Kies één reactie',
  required: 'Verplicht',
  aboutPrivacyTitle: 'Privacy',
  aboutPrivacy:
    'Deze app bewaart voortgang en resultaten alleen in de lokale opslag van deze browser. Er gaan geen student- of cliëntgegevens naar een server. Er is geen analyse, advertentie of tracking. Je kunt resultaten zelf verwijderen.',
  aboutDisclaimerTitle: 'Educatief gebruik',
  aboutDisclaimer:
    'Alle cliënten en patiënten, waaronder Erik de Vries (logopedie) en meneer de Vries (verpleegkunde), zijn fictief. De training is bedoeld voor onderwijs. Gebruik de app niet om echte patiënten te beoordelen of te behandelen.',
  aboutClearData:
    'Wis lokale gegevens via de browserinstellingen voor deze site, of verwijder afzonderlijke resultaten in Eerdere resultaten.',
  competencyLabels: {
    adaptedCommunication: 'Aangepaste communicatie',
    historyTakingAndGoals: 'Anamnese en cliëntdoelen',
    observation: 'Observatie',
    clinicalReasoning: 'Klinisch redeneren',
    empathyAndProfessionalBehaviour: 'Empathie en professioneel gedrag',
  },
  emotionLabels: {
    neutral: 'Neutraal',
    listening: 'Luistert',
    speaking: 'Spreekt',
    thinking: 'Denkt na',
    confused: 'Verward',
    frustrated: 'Gefrustreerd',
    fatigued: 'Vermoeid',
    reassured: 'Opgelucht',
  },
} as const;
